### ISSUE TITLE
[Feat Request]: UIKit support

### ISSUE THREAD

**Issue by BayramInanc** [ra1028/swiftui-atom-properties#37]
### Checklist

- [X] Reviewed the README and documentation.
- [X] Checked existing issues & PRs to ensure not duplicated.

### Description

Any plan to support in UIKit?

### Example Use Case

It would be great if we can use it in UIKit app

**Comment by ra1028** [comment]
Since this library fully depends on EnvironmentValues, I think applying it to UIKit hurts the concepts.
When I thought about that feasibility previously I thought that doing DI of the state store could provide equivalent functionality, but I don't know if that is the preferred way over other libraries.
